### ISSUE TITLE
not able to divide two placeholders

### ISSUE THREAD

**Issue by Blcbby** [Andre601/Math-Expansion#10] opened 2022-03-26 05:26 UTC
### I confirm that...

- [X] I use the latest version of the expansion. [[Expansion Page](https://api.extendedclip.com/expansions/math/) | [Changelog](https://github.com/Andre601/Math-Expansion/blob/master/CHANGELOG.md)]
- [X] The issue is not caused by PlaceholderAPI or any other plugin or expansion
- [X] Any used placeholder works as intendet (`/papi parse me <placeholders>`)

### Description

so dividing one placeholder by a regular number works, but as soon as i try to divide two placeholders (both with values), the math doesnt feel like wanting to actually divide them (btw i am using paper as spigot plugins still work perfectly on paper, and its just less laggy in general so i feel like its better in a sense)

### Logs

```text
none
```

### Math Expansion version

```text
Placeholder expansion info for: math
Status: Registered
Author: Andre_601
Version: 1.3.2
```

### PlaceholderAPI version

```text
PlaceholderAPI version 2.11.1
An awesome placeholder provider!
Author: HelpChat
```

### Server version

```text
This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are running the latest version
```

**Comment by Andre601** [comment] 2022-03-26 08:28
Please actually provide the placeholder(s) you use and that aren't working.

**Comment by Blcbby** [comment] 2022-03-26 12:58
mb
the placeholders string i used was
%math_{objective_score_{wins}}/{objective_score_{losses}}%
both are set to 1

**Comment by Andre601** [comment] 2022-03-26 13:31
Duplicate of #9

**Closed by Andre601** 2022-03-26 13:31 UTC
